In [35]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [51]:
dataset=pd.read_csv('slip_25.csv')
print(dataset.isnull().sum())
dataset = dataset.drop(columns=['TransactionID', 'AccountID', 'DeviceID', 'IP Address'])
dataset = dataset.drop(columns=['TransactionDate', 'PreviousTransactionDate'])


TransactionID              0
AccountID                  0
TransactionAmount          0
TransactionDate            0
TransactionType            0
Location                   0
DeviceID                   0
IP Address                 0
MerchantID                 0
Channel                    0
CustomerAge                0
CustomerOccupation         0
TransactionDuration        0
LoginAttempts              0
AccountBalance             0
PreviousTransactionDate    0
dtype: int64


In [52]:
X=dataset.iloc[:,dataset.columns!='TransactionType'].values
y=dataset.iloc[:,dataset.columns=='TransactionType'].values.ravel()

In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [54]:
print(dataset.columns)

Index(['TransactionAmount', 'TransactionType', 'Location', 'MerchantID',
       'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration',
       'LoginAttempts', 'AccountBalance'],
      dtype='object')


In [55]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

co = ColumnTransformer(
    transformers=[
        ("encoder", OneHotEncoder(sparse_output=False), [1, 2, 3, 5])  # categorical column indices
    ],
    remainder="passthrough"
)
X = co.fit_transform(X)


In [56]:
print(X)

[[0.0 0.0 0.0 ... 81 1 5112.21]
 [0.0 0.0 0.0 ... 141 1 13758.91]
 [0.0 0.0 0.0 ... 56 1 1122.35]
 ...
 [0.0 0.0 0.0 ... 146 1 3382.91]
 [0.0 0.0 0.0 ... 19 1 1776.91]
 [0.0 0.0 0.0 ... 93 1 131.25]]


In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [58]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [59]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
kernels=['linear','poly','rbf','sigmoid']
best_acc=0
best_acc_kernel=''
accuracies=[]

for k in kernels:
    print("========================= Kernel : ",k.upper()," =======================")

    s=SVC(kernel=k,random_state=0)
    s.fit(X_train,y_train)

    y_pred=s.predict(X_test)

    c=confusion_matrix(y_test,y_pred)
    print("Confusion matrix : \n ",c)

    acc=accuracy_score(y_test,y_pred)*100
    print("Accuracy : ",round(acc,2))
    accuracies.append(acc)

    if acc>best_acc:
        best_acc=acc
        best_acc_kernel=k

print("\n\nbest kernel : ",k.upper())
print("Accuracy : ",best_acc)

========================= Kernel :  LINEAR  =======================
Confusion matrix : 
  [[  0 108]
 [  0 395]]
Accuracy :  78.53
========================= Kernel :  POLY  =======================
Confusion matrix : 
  [[  0 108]
 [  9 386]]
Accuracy :  76.74
========================= Kernel :  RBF  =======================
Confusion matrix : 
  [[  0 108]
 [  0 395]]
Accuracy :  78.53
========================= Kernel :  SIGMOID  =======================
Confusion matrix : 
  [[  0 108]
 [  0 395]]
Accuracy :  78.53


best kernel :  SIGMOID
Accuracy :  78.52882703777337


In [60]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

# Load your dataset
df = pd.read_csv('slip_25.csv')

# Encode categorical target (Credit/Debit)
le = LabelEncoder()
df['TransactionType'] = le.fit_transform(df['TransactionType'])

# Select numeric features
X = df[['TransactionAmount', 'CustomerAge', 'TransactionDuration', 'AccountBalance']]
y = df['TransactionType']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Scale features
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Apply SVM with Linear kernel
svc_linear = SVC(kernel='linear')
svc_linear.fit(X_train, y_train)
y_pred_linear = svc_linear.predict(X_test)

# Apply SVM with Polynomial kernel
svc_poly = SVC(kernel='poly', degree=3)
svc_poly.fit(X_train, y_train)
y_pred_poly = svc_poly.predict(X_test)

# Evaluate
print("=== Linear Kernel ===")
print(confusion_matrix(y_test, y_pred_linear))
print("Accuracy:", accuracy_score(y_test, y_pred_linear))

print("\n=== Polynomial Kernel ===")
print(confusion_matrix(y_test, y_pred_poly))
print("Accuracy:", accuracy_score(y_test, y_pred_poly))


=== Linear Kernel ===
[[  0 108]
 [  0 395]]
Accuracy: 0.7852882703777336

=== Polynomial Kernel ===
[[  0 108]
 [  0 395]]
Accuracy: 0.7852882703777336
